#!Replace `us-central1-docker.pkg.dev` with your region specific Container Registry domain

steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/aerobic-gantry-387923/compass-utd/fastapi', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/aerobic-gantry-387923/compass-utd/fastapi']
images:
- us-central1-docker.pkg.dev/aerobic-gantry-387923/compass-utd/fastapi